### ISSUE TITLE
How to use NODE_ENV=production

### ISSUE THREAD

**Issue by sorin89** [strapi/strapi-docker#103]
Hello.
strapi-docker always starts in development (info Environment: development), cannot make it start with NODE_ENV=production

**Comment by facundofarias** [comment]
By using this repo as a reference, I have built my own Dockerfile by only using npm, in that way I can specify the environment. I believe is the way to go. If you want @sorin89 I can share it in a separate repo.

Cheers

**Comment by sorin89** [comment]
It would be great if you could share your repo! Thank you so much!

**Comment by FDiskas** [comment]
`export NODE_ENV=production`

**Comment by petarmihaylov** [comment]
You can add 
`- NODE_ENV=production`
to the environment section of the `docker-compose.xml` file:

```
version: '3'

services:
  api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      [ ... omitted for brevity ... ]
      - HOST=localhost
      - NODE_ENV=production
    ports:
      - 1337:1337
    vol...
```
