### ISSUE TITLE
strapi image created under root user

### ISSUE THREAD

**Issue by Laazarus** [strapi/strapi-docker#107]
Hello, I am sorry if this is not a problem, it could be me being very expert on strapi (I am evaluating it for a project I have to start) and Docker ( i have used it only a couple of times).

When I run docker-compose up command everything goes well and the environment get set up and run fine my only problem is that the strapi app folder and the db folder are created under the root ownership making it impossible to be opened on an IDE such us Visual studio code in order to modify the project (e.g it is impossible to install a new file uploader provider if not from inside the container).

Again this might me me having done something wrong but I have tried everything and I canot find a solution.

I am running under Linux Ubuntu 18.0.4 docker is not running with sudo but under a docker group which my own user belongs too.

I really appreciate you help and thanks for this repo :)

Regards

**Comment by FDiskas** [comment]
“Running a Docker container as a non-root user” by Lucas Wilson-Richter https://link.medium.com/19C6L1OTxV

**Comment by Laazarus** [comment]
Thanks I am trying a bit everything but I could not still figure out a way to make thing fully working.
After the creation I change the owner of the volume in the host machine using this command 
`sudo chown -R $USER`
This seems to work  fine the only issue I am having is the host folder the strapi folder under npm module is not present. 
This is a problem because i I want to install aws file upload or any other plug in for strapi I have to install it inside the container.

Is this expected?

Is anywhere a procedure I can follow to install the image in the correct way?

Thanks again for your support and for this image :)

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Comment by guicara** [comment]
This issue is not resolved :(
Please see #263

**Comment by alexandrebodin** [comment]
Reopening the original issue and closing the duplicate one #263. 

If someone wants to help out on this topic let me know. 

Until we find a fix, I would recommend you create a custom Dockerfile and set it up how you actually want it.

**Comment by RussellSanders1** [comment]
Any updates on what could be done to fix this?

**Comment by lucasnasm** [comment]
temporary solution, @RussellSanders1 

First create the application folder, Ex:  app.

run the command below to find out your user id
```shell
id -u
```

change the user value in docker-compose.yml to your user ID.

in my case "user:group" would be 1000:1000

Ex: 

``` yml
version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    user: 1000:1000
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
```
