### ISSUE TITLE
Cannot connect to db (mongo) when use docker-compose.yml

### ISSUE THREAD

**Issue by Truemedia** [strapi/strapi-docker#115]
I seem to be having problems using strapi as a container in a custom box I'm building.

Here is my docker-compose.yml
```yaml
version: '3'

networks:
  mindstack:

volumes:
  mongodb_data:
    driver: local

services:
  mindstack_cms:
    image: strapi/strapi
    ports:
      - "1337:1337"
    environment:
      HOST: localhost
      DATABASE_HOST: strapi-db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: example
    networks:
      - mindstack
    depends_on:
      - mindstack_db

  mindstack_db:
    container_name: mindstack_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
        - mindstack
```

Mongo seems to load fine but when the strapi install starts it seems to only get as far as this:
```bash
mindstack_cms_1  | 🚀 Starting to create your Strapi application.
mindstack_cms_1  | 
mindstack_cms_1  | Database determined by CLI args: mongo
mindstack_cms_1  | 
mindstack_cms_1  | ⏳ Testing database connection...
mindstack_cms_1  | It might take a minute, please have a coffee ☕️
mindstack_cms_1  | ⚠️  Database connection has failed! Make sure your database is running.
```

Iv'e checked out all other open/closed issues relating to db but none seem to point to a working solution for this. Any ideas? thanks
