### ISSUE TITLE
Cannot connect to db (mongo) on AWS Fargate

### ISSUE THREAD

**Issue by p0fi** [strapi/strapi-docker#116]
I can't connect to to MongoDB when running the container on AWS Fargate. I enabled debug logs and that is what I get:

```
⏳ Testing database connection...
⚠️ Database connection has failed! Make sure your database is running.
🐛 Full error log:
{ Error: connect ECONNREFUSED 127.0.0.1:27017
 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
 errno: 'ECONNREFUSED',
 code: 'ECONNREFUSED',
 syscall: 'connect',
 address: '127.0.0.1',
 port: 27017 }
```

As I understood on AWS Fargate all containers share the same network space so the db host should be localhost. Here is my `docker-compose.yml`

```
version: '3'

services:
  api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=localhost
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 80:80
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
```

Does anybody know how to resolve this?
