### ISSUE TITLE
 Infinite loading to acesses admin dashboard with docker-compose

### ISSUE THREAD

**Issue by gabrielsoaresm94** [strapi/strapi-docker#167]
**Describe the bug**
After up the docker containers with the database and strapi, when accessing the route `localhost:1337/admin` with the dashboard there is a load that does not stop.

**Steps to reproduce the behavior**
1. If you do not have Docker and Docker-compose, install with these steps: https://docs.docker.com/get-started/
2. Once installed, create a folder named `project`.
3. Create a docker-compose.yml file.
4. Put the code in * Code snippets * down here in the docker-compose.yml file.
5. In the `project` folder, open the terminal and type the command `docker-compose up`
6. After loading containers, type in browser `localhost: 1337 / admin` to see the problem

**Expected behavior**
Access the `locahost: 1337 / admin` route to be able to create the admin and gain access to the dashboard.

**Code snippets**
The code that I use in docker-compose.yml file:
```
version: '3'

services:
  api:
    depends_on:
      - db
    image: strapi/strapi
    restart: unless-stopped
    # container_name: strapi
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: project
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    ports:
      - 1337:1337
    volumes:
      - ./project/strapi:/usr/src/api/strapi-app

  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "strapi"
      MYSQL_USER: "strapi"
      MYSQL_PASSWORD: "strapi"
      MYSQL_DATABASE: "project"
    volumes:
      - ./project/db:/var/lib/mysql

#  react:
#    image: front
#    build: ./front
#    ports:
#      - "3000:3000"
```

**System**
- Node.js version: 11.1.0-alpine (Strapi Docker Image)
- NPM version:
- Strapi version: Latest (Strapi Docker Image)
- Database: Mysql 5.7 (Mysql Docker Image)
- Operating system: Ubuntu 18.04.2 LTS 

**Additional context**
I am using the strapi image with this Dockerfile (https://hub.docker.com/r/strapi/strapi/dockerfile) and followed the guidelines in this tutorial: https://www.youtube.com/watch?v=k5KdguLX4NE . I adapted it to a Mysql image, different from MariaDB, which it uses.

As others had a similar problem, but it did not involve Docker, being almost new, I put an Issue in Strapi's main repository, but, discovering this one, I also decided to ask for help here.

**Comment by lauriejim** [comment]
Hello @gabrielsoaresm94 !
I just tried your instructions and it works like a charm on my side.
[📺 Here](https://www.loom.com/share/55bb328c64bd4363bd3257a7ca60f454) is a record of what I did.
Let me know if I messed up something.

**Comment by gabrielsoaresm94** [comment]
@lauriejim thanks for your support and your work to produce and up the video, I'm so glad.
But unfortunately here is still not working, I created another project to up new containers, but still failed. Is this a problem with the OS? Or with some permission?

I uploaded an image with the latest logs, but if need be I can try to make a video later. Basically redid the instructions.

![](https://i.imgur.com/HndugoL.png)

**Comment by alexandrebodin** [comment]
Hi @gabrielsoaresm94, 

I think your issue might be because the strapi container is started before the mysql container, thus the bootstrap process that creates the user permissions cannot create them and you get a 403 error on the call to `/users-permissions/init`.

Make sure to start your container with a `wait-for`command. 
You can find some example in the docker documentation [here](https://docs.docker.com/compose/startup-order/)

**Comment by zzkevinlim** [comment]
This issue will persist, I have found the solution here https://github.com/strapi/strapi/issues/3284#issue-445319771 (note: the json file is now a different directory)

**Comment by gabrielsoaresm94** [comment]
Guys finally managed to solve and run here. I researched `wait-for` and found a tutorial for adding `environment` to the docker-compose file.

It was like this the final version, with `environment` and `hostname`:

```
version: '3'

services:
  api:
    depends_on:
      - db
    image: strapi/strapi
    restart: unless-stopped
    # container_name: strapi
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: project
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    ports:
      - 1337:1337
    volumes:
      - ./project/strapi:/usr/src/api/strapi-app
    environment:
      WAIT_HOSTS: mysql:3306

  db:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "33060:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "strapi"
      MYSQL_USER: "strapi"
      MYSQL_PASSWORD: "strapi"
      MYSQL_DATABASE: "project"
    volumes:
      - ./project/db:/var/lib/mysql
```
Thanks for the great help @lauriejim , @alexandrebodin and @zzkevinlim.
