### ISSUE TITLE
Infinite spinner

### ISSUE THREAD

**Issue by Macke97** [strapi/strapi-docker#177]
I am running a docker-compose project with a nginx proxy that proxies requests to my docker-compose services (nginx is part of my docker-compose). When I am running strapi behind nginx, the only thing I can see is an infinite loading spinner. The scripts are loaded but nothing happens. What is the correct configuration to make this work?

![image](https://user-images.githubusercontent.com/22647302/74111531-726a4980-4b95-11ea-9f25-7834f55d4e5a.png)

Trying proxying trough my node.js app since nginx did not work for, but same result. Proxying /admin to http://strapi:1337 (docker-compose network)

**Comment by alexandrebodin** [comment]
Hi @Macke97,

I do not have enough informations to help you. You will need to share your docker configurations and nginx config too so I can see what's up.

**Comment by Macke97** [comment]
# Docker compose

```yml
version: '3'

services:
    api:
        build: ./services/api
        volumes:
            - ./services/api:/app
        environment:
            - PORT=80
            - HOST=${HOST:-http://localhost:3000}
            - WP_HOST=${WP_HOST:-http://wp.boilerplate.se.localhost}

    frontend:
        build: ./services/frontend
        environment:
            - SCRIPT_VERSION=0-dev
            - HOST=${HOST:-http://boilerplate.se.localhost}
        volumes:
            - ./services/frontend:/app
    nginx:
        build: ./services/nginx
        ports:
            - 3000:80
        depends_on:
            - api
            - frontend
            - strapi
        restart: on-failure

    redis:
        image: redis

    strapi:
        image: strapi/strapi
        depends_on:
            - mysql
        environment:
            NODE_ENV: production
            DATABASE_CLIENT: mysql
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: strapi
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
            PROXY_HOST: localhost // Do I need these?
            PROXY_PORT: 8000
        volumes:
            - ./services/strapi:/srv/app
    mysql:
        image: mysql:5.7
        volumes:
            - ./data:/var/lib/mysql
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=dettavarkul
            - MYSQL_DATABASE=strapi
            - MYSQL_USER=strapi
            - MYSQL_PASSWORD=strapi

```

# Nginx
```nginx
events {
  worker_connections  4096;  ## Default: 1024
}

http {
    server {
        listen 80;
         location /admin {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass_request_headers on;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://strapi:1337;
        }
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass_request_headers on;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://frontend:80;
        }
    }
}
```
