### ISSUE TITLE
deploy strapi connected to mongodb Atlas

### ISSUE THREAD

**Issue by juliensl** [strapi/strapi-docker#188]
Hi everybody, 

I found lots of tutorials to launch strapi with docker using a mongo database locally, but I cannot find a docker tutorial to connect him to an external database :/

What I did : 
- start a free cluster on mongoDB atlas, set a user and authorize all ip address
- initiate a vm on Azure with ubuntu 18
- install docker and docker-compose
- clone the strapi-docker repo
- copy past the docker-compose.yml example from "examples/mongo/" to "base/"
- edit the docker-compose.yml like this : 

```
version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=myUrlFromMongoDBAtlas/test?retryWrites=true&w=majority
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=mypassword
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
```

- launch docker-compose up

docker is trying to start strapi but go the error : 
```
strapi    | ✔ Webpack: Compiled successfully in 28.88s
strapi    | [2020-03-27T15:58:55.465Z] debug ⛔️ Server wasn't able to start properly.
strapi    | [2020-03-27T15:58:55.467Z] error Error connecting to the Mongo database. Server selection timed out after 30000 ms
strapi exited with code 1
```

I do not understand what I did wrong :'( 

Is it a problem coming from the repo or is it me ?

**Comment by juliensl** [comment]
Hi again ! :) 

I saw that mongodb Atlas is a little bit complex about authentication, replica, etc, so, I tried with mlab to delete complexity, but it still does not working :'( 

This is my docker-compose.yml : 
```
version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=ds042459.mlab.com
      - DATABASE_PORT=42459
      - DATABASE_NAME=strapi-gatsby
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=myPasswordWithoutAnySymbols (only letters and numbers)
      - DATABASE_AUTHENTICATION_DATABASE=strapi-gatsby
      - DATABASE_SSL=false
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    command: 'strapi start'
```

This is a screen of my mlab configuration : 
![mlab](https://user-images.githubusercontent.com/43228020/77791098-539d1500-7066-11ea-9a2d-6034603c94d2.png)

and to find the port : 
![inline_connection](https://user-images.githubusercontent.com/43228020/77791163-74656a80-7066-11ea-98fb-8b28a1bea79d.png)

No mistakes with username and password, I checked them twice and I can easily connect Robo3T to the database... :( 

I'll try with a manual strapi install, I keep you in touch

**Comment by juliensl** [comment]
Ahhhhhh !!!! I found without Docker ! :D 

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "mongoose",
      "settings": {
        "client":"mongo",
        "host": "ds042459.mlab.com",
        "port": "42459",
        "database": "strapi-gatsby",
        "username": "strapi",
        "password": "myPasswordWithoutAnySymbols"
      },
      "options": {
        "authenticationDatabase":"strapi-gatsby",
        "ssl":false
      }
    }
  }
}
```

The only different that I see, is the definition of the connector :/ 

I really want to dokerise this app, if you have any idea I'm listening :hugs:

**Comment by alexandrebodin** [comment]
Hi @juliensl you can use this doc to know how to pass env vars in those parameters :) 
https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#dynamic-configurations

**Comment by alexandrebodin** [comment]
you might also want look at our guide on using mongodb atlas first :) https://www.youtube.com/watch?v=HHnRsZwFmR8&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=7&t=0s

**Comment by alexandrebodin** [comment]
Closing this issue for now as it doesn't seem to be related to the docker image itself but configuration of strapi.

**Comment by iKethavel** [comment]
Hello, @alexandrebodin!

Looks like approaches to replace mongodb atlas connetion string from docs and video works fine when we launch app via yarn or npm.  
But what about docker? I still do not understand how to make it work :(
I could connect to this db via gui or mongoose
```
version: '3'
services:

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_URI: mongodb+srv://arhe1:<password>@arhetericaclaster-5s8wz.mongodb.net/strapi?retryWrites=true&w=majority
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
```

**Comment by juliensl** [comment]
Does anybody succeed to connect Strapi-Docker to MogoDB Atlas ?

**Comment by LuisFalconMX** [comment]
# Strapi + MongoDB Atlas + Docker + Docker Compose.
Here is a guide that you can also find in [my repository](https://github.com/LuisFalconMX/strapi) about how to use Strapi + Mongodb Atlas + Docker + Docker Compose. Read all the steps carefully, please. I will be attentive to the doubts that may arise from this guide.

[ [Ver esta guía en español](https://github.com/LuisFalconMX/strapi/blob/main/docs/README.es.md) ]

## Prerequisites
First we go to MongoDB Atlas, we log in and from the main menu we select a project. If you don't have a project, create one.
![MongoDB Atlas - Tutorial 1](https://github.com/LuisFalconMX/strapi/blob/main/docs/images/1-mongodb-atlas-tutorial.png?raw=true)

Then we go to the section **Database Access**.
![MongoDB Atlas - Tutorial 2](https://github.com/LuisFalconMX/strapi/blob/main/docs/images/2-mongodb-atlas-tutorial.png?raw=true)

We click on **Add New Database User**
![MongoDB Atlas - Tutorial 3](https://github.com/LuisFalconMX/strapi/blob/main/docs/images/3-mongodb-atlas-tutorial.png?raw=true)

We create a new user with the name and password. We must make sure to assign the necessary permissions to be able to read and write to the database. When finished we click on **Add User**
![MongoDB Atlas - Tutorial 4](https://github.com/LuisFalconMX/strapi/blob/main/docs/images/4-mongodb-atlas-tutorial.png?raw=true)

We return to the **Clusters** section and click on the **CONNECT** button
![MongoDB Atlas - Tutorial 5](https://github.com/LuisFalconMX/strapi/blob/main/docs/images/5-mongodb-atlas-tutorial.png?raw=true)

We select **Connect your application**
![MongoDB Atlas - Tutorial 6](https://github.com/LuisFalconMX/strapi/blob/main/docs/images/6-mongodb-atlas-tutorial.png?raw=true)

We configure the first field in **Node js** with version **3.0 or later** and copy the code provided below.
![MongoDB Atlas - Tutorial 7](https://github.com/LuisFalconMX/strapi/blob/main/docs/images/7-mongodb-atlas-tutorial.png?raw=true)

The following code will help us to configure strapi with MongoDB Atlas. Make sure to use yours, this is just an example.
``` bash
mongodb+srv://strapi:<password>@main.hfhwg.mongodb.net/<dbname>?retryWrites=true&w=majority
```

The above code contains the following fields:
``` bash
conection-type: mongodb+srv
host: main.hfhwg.mongodb.net
dbname: <dbname>
username: strapi
password: <password>
```
**Identify the same fields but with your code so that you can continue with the tutorial.**

For the **dbname** field, you will specify which is the database you want to connect to and for the **password** field it will be the password that you set for the user you created. **Follow the tutorial so you can see in detail how these fields are used**.

## 1 - Initialize the project
Run the following command to initialize the project. Change **my-project** to the actual name of your project.

``` bash
npx create-strapi-app my-project
```

Then select the option **Custom (manual settings)**
``` bash
? Choose your installation type
 Quickstart (recommended)
> Custom (manual settings)
```

Now select **mongo**
``` bash
? Choose your default database client
 sqlite
 postgres
 mysql
> mongo
```

Insert the name of the database. **If it doesn't exist, a new one will be created with the name you provide.**
``` bash
? Database name: strapi
```

The host is found in the code we got from MongoDB Atlas (**See the prerequisites above**). **Make sure to place yours, the following is an example.**
``` bash
? Host: main.hfhwg.mongodb.net
```

We put **true** since it was indicated in the MongoDB Atlas code that the **connection-type** is **mongodb + srv**
``` bash
? +srv connection: true
```

The default port in mongodb is **27017**
``` bash
? Port (It will be ignored if you enable +srv): 27017
```

Now we will put the username we created in MongoDB Atlas. Make sure to use yours.
``` bash
? Username: strapi
```

Then we put the password for the user that we used previously.
``` bash
? Password: ****
```

Here we will only press enter since we will select the second option which is blank
``` bash
? Authentication database (Maybe "admin" or blank):
```

Finally we will put **y** to enable a connection through ssl
``` bash
? Enable SSL connection: y
```

Ready. We wait for the project to finish installing and we can access the following url where the strapi panel will be.

[http://localhost:1337](http://localhost:1337)

## 2 - Environment Variables
We must configure environment variables to be able to use them in docker and docker compose.

First we are going to edit the file ```./config/database.js``` where we will put the environment variables with their default values.

``` javascript
module.exports = ({ env }) => ({
 defaultConnection: "default",
 connections: {
   default: {
     connector: "mongoose",
     settings: {
       host: env("DATABASE_HOST", "127.0.0.1"),
       srv: env.bool("DATABASE_SRV", false),
       port: env.int("DATABASE_PORT", 27017),
       database: env("DATABASE_NAME", "strapi"),
       username: env("DATABASE_USERNAME", "user"),
       password: env("DATABASE_PASSWORD", "password"),
     },
     options: {
       authenticationDatabase: env("AUTHENTICATION_DATABASE", null),
       ssl: env.bool("DATABASE_SSL", false),
     },
   },
 },
});
```

Then in the file ``` ./config/server.js ``` we remove the token that is in the variable ADMIN_JWT_SECRET. Make sure to keep it in a safe place, you will need it to authenticate. Do not lose it!.

``` javascript
module.exports = ({ env }) => ({
 host: env("HOST", "0.0.0.0"),
 port: env.int("PORT", 1337),
 admin: {
   auth: {
     secret: env("ADMIN_JWT_SECRET"),
   },
 },
});
```

With this we will have the environment variables ready.

## 3 - Docker and Docker Compose
Now we will configure the file ``` ./Dockerfile ``` in the root of the project with the following content.
``` dockerfile
FROM node:14.15.4
COPY [".", "/usr/src/"]
WORKDIR /usr/src/
RUN npm install
CMD [ "npm", "start" ]
EXPOSE 1337
```

We also need the ``` .dockerignore ``` in the root of the project with the following content.
```
.git
.env
Dockerfile
.tmp
.cache
```

Let's test the image by building and running a container with the environment variables for production. We will use the MongoDB Atlas credentials. Check out the prerequisites above.
``` bash
# shell
docker build -t my-strapi-image .
```

Replace the values with your MongoDB Atlas credentials, and put the **token** you saved earlier in ADMIN_JWT_SECRET.
``` bash
# shell
docker run --name my-app -p 1337:1337 \
-e DATABASE_HOST=my-host \
-e DATABASE_SRV=true \
-e DATABASE_NAME=my-db \
-e DATABASE_USERNAME=my-username \
-e DATABASE_PASSWORD=my-pass \
-e DATABASE_SSL=true \
-e ADMIN_JWT_SECRET=token \
my-strapi-image
```

When the container finishes running, access the url: [http://localhost:1337](http://localhost:1337). If you can see and enter strapi then everything is fine.

Now stop the container and configure docker-compose.

We continue with the file ```./docker-compose.yml``` located at the root of the project with the following content. The only variable you will have to change is ADMIN_JWT_SECRET for the token you saved earlier.
``` yml
version: '3'
services:
  strapi:
    build: .
    command: npm run develop
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      ADMIN_JWT_SECRET: token
    volumes:
      - .:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.11-bionic
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./.tmp/data:/data/db
```

Now let's try docker compose with the following command.
``` bash
docker-compose up
```

Wait for the image to build and both containers to run. When they finish access the url: [http://localhost:1337](http://localhost:1337)

With the previous files already configured we will have everything ready to work in development with docker compose and in production with the image declared in the Dockerfile.

**Comment by malithmcr** [comment]
Make sure you installed `mongoose` and `strapi-connector-mongoose` then use this docker file:
```
version: '3'

services:
  api:
    image: strapi/strapi
    restart: unless-stopped
    container_name: strapi
    env_file: .env
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mongo
    ports: 
      - 1337:1337
    volumes:
      - ./app:/srv/app
```

database.js should be like this:

```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        uri: env('DATABASE_URI'),
      },
      options: {
        ssl: true,
      },
    },
  },
});
```

**Comment by penji2** [comment]
Hi,

an image strapi/starpi calls `strapi new` under the hood while starting container, which eventually creates database.js which has details of connection to a database. If we assume that your connection string has value: "mongodb+srv://your-db-user:your-password@yourclustername.something.mongodb.net/test-strapi"

If you want to connect to a Atlas MongoDB cluster, your database.js file should look something like this:
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        host: env('DATABASE_HOST', 'yourclustername.something.mongodb.net'),
        srv: env.bool('DATABASE_SRV', true),
        port: env.int('DATABASE_PORT', 27017),
        database: env('DATABASE_NAME', 'test-strapi'),
        username: env('DATABASE_USERNAME', 'your-db-user'),
        password: env('DATABASE_PASSWORD', 'your-password'),
      },
      options: {
        authenticationDatabase: env('AUTHENTICATION_DATABASE', null),
        ssl: env.bool('DATABASE_SSL', true),
      },
    },
  },
});

```
correspondingly your docker-compose.yml file should look like this:

```
version: "3"

services:
  yourservice:
    image: strapi/strapi
    container_name: yourcontainername
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: test-strapi
      DATABASE_HOST: yourclustername.something.mongodb.net
      DATABASE_PORT: 27017
      DATABASE_SSL: true
      DATABASE_SRV: true
      DATABASE_USERNAME: your-db-user
      DATABASE_PASSWORD: your-password
```


the key point is to include DATABASE_SRV variable.

hope it helps,
cheers
