### ISSUE TITLE
Add Option to specify Authentication DB in yml file

### ISSUE THREAD

**Issue by mindpivot** [strapi/strapi-docker#19]
I've been unable to use this image to connect to a custom MongoDB. I am receiving authentication errors using known working credentials.

I am able to connect to the same DB using a non-docker install of the same version (alpha 12.2) of Strapi directly from the command line. Best I can tell, the main difference is command line install with the prompts asks for the Authentication DB separately.

Would there be some way to include that as an optional environment variable to set? Or, if it is already possible with the current image a few pointers to get it working?

Thanks!

**Comment by lucaperret** [comment]
@Aurelsicoko could it be linked to Strapi ? Is the `strapi new` working on an non-empty database ?

**Comment by mindpivot** [comment]
@lucaperret When I tried to run the docker image the database was empty. `strapi new` works well directly from the VM I used to run it from the CLI. (i *have* run into a problem keeping it running or restarting the process which I haven't had time to investigate)

**Comment by Aurelsicoko** [comment]
@lucaperret I don't know how it could be related to Strapi. What are the main differences between the command `strapi new` without the prompts?

**Comment by lucaperret** [comment]
Hi @mindpivot, we should take into account your database configuration.
In Strapi it's prompted to the user https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/before.js#L181-L196.
Do you want to make the PR to:
- add `DATABASE_AUTHENTICATION` (default false) and `DATABASE_ENABLE_SSL` (default false) environment variables in the [docker-compose](https://github.com/strapi/strapi-docker/blob/master/docker-compose.yml#L14) file.
- change the entrypoints to take these variables into account when calling the `strapi new` in the [strapi.sh](https://github.com/strapi/strapi-docker/blob/master/strapi.sh#L22) file.

In any case, I'll add this feature next week.

**Comment by lucaperret** [comment]
Environment variables are passed to the `strapi new` via the `strapi.sh` entrypoint.
But it should be also considered in the Strapi's CLI package: https://github.com/strapi/strapi/search?q=dbport&unscoped_q=dbport

**Comment by lucaperret** [comment]
This update can be done when this docker image use Strapi `3.0.0-alpha.12.2`. We'll do our best asap !

**Comment by lucaperret** [comment]
Could you retry with the last docker image that includes the `v3.0.0-alpha.12.4` ?

**Comment by mindpivot** [comment]
@lucaperret I'll give it a shot this weekend

**Comment by lucaperret** [comment]
Sorry, it should be implemented in the `strapi.sh` entrypoint to pass these arguments to the CLI, and in the Strapi's CLI code. I'll do it in July...

**Comment by mindpivot** [comment]
@lucaperret let me know when it's ready, i'll try it out

**Comment by vaskort** [comment]
There is PR now open for this in Strapi's CLI code: https://github.com/strapi/strapi/pull/1555

**Comment by lauriejim** [comment]
We update to `alpha.13`, so you can try to make updates for you new options

**Comment by dannydtk** [comment]
@lucaperret Hey, could you please add these options to the CLI and docker-compose.yml? It works locally with `--dbauth=` and `dbssl=`  flags.

**Comment by lucaperret** [comment]
Hello all,
I've added two environment variables for these purpose: `DATABASE_SSL ` & `DATABASE_AUTHENTICATION_DATABASE `. Try with the latest docker image.

**Comment by bruce0205** [comment]
Hi @lucaperret , I got below error message with 'strapi/strapi:v3.0.0-alpha.13.0.1' image.
```
Testing database connection..
(node:5) UnhandledPromiseRejectionWarning: MongoError: Authentication failed.
Database connection has failed! Make sure your database is running.
```
my docker-compose.yml is: 
```
version: '3'

services:
  strapi:
    image: strapi/strapi:v3.0.0-alpha.13.0.1
    container_name: strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_ENABLE_SSL=false
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_AUTHENTICATION_DATABASE=admin
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin123
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - strapi_data:/usr/src/api/strapi-app
    networks:
      - default
      - database
    restart: always

volumes:
  strapi_data:
networks:
  database:
    external:
      name: mongo-net
```
