### ISSUE TITLE
Only the index page can be accessed while in watch-admin mode

### ISSUE THREAD

**Issue by pitou** [strapi/strapi-docker#195]
Hi!

I tried two different approaches:

Via docker-compose.yml directly, starting from `strapi/strapi`

```
strapi-app-development:
    image: strapi/strapi:3.0.0-beta.19.5-node12-alpine
    container_name: strapi-app-development
    ports:
      - ${APP_EXTERNAL_PORT}:1337
    working_dir: /srv
    command: >
      bash -c "strapi new app --no-run --quickstart
        && cd app
        && strapi develop --watch-admin"
```

And after building a new image, starting from `strapi/base`

```
FROM strapi/base:12-alpine

RUN yarn global add strapi@3.0.0-beta.19.5

WORKDIR /srv/app

RUN strapi new . \
  --quickstart \
  --no-run

RUN strapi build
```
and then in the docker-compose.yml:

```
strapi-app-development-from-base:
    image: <my-previously-built-image>
    container_name: strapi-app-${ENV}-from-base
    ports:
      - ${APP_EXTERNAL_PORT}:1337
    volumes:
      - ./admin:/srv/app/admin
    working_dir: /srv/app
    command: strapi develop --watch-admin
```

In both cases, I can reach the index page at `http://127.0.0.1:1337` or `http://localhost:1337`, but any other linked page gives me the error:
```
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

Actually, the case that interests me the most is the second one, since it's the only one that allows me to mount the `admin` directory.

Thanks!
