### ISSUE TITLE
Sendmail is not working with docker

### ISSUE THREAD

**Issue by jeremy-hubsy** [strapi/strapi-docker#199]
Hello,

I'm using docker with strapi.

I'm in development mode and the sendmail feature from Strapi is not working....

Strapi doesn't send an email if a User register or forget his password...

Here is my docker-compose.yml file.

```
version: "3"

services:
  strapi:
    container_name: strapi
    image: strapi/strapi:3.0.0-beta.18.3-node12
    ports:
      - 1337:1337
    networks:
      - dev
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c 'npm install && npm run develop'

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./db:/var/lib/mariadb
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    networks:
      - dev
networks:
  dev:
    driver: bridge
volumes:
  node_modules:
```
