### ISSUE TITLE
How do you configure a MongoDB replica set connection string in Docker?

### ISSUE THREAD

**Issue by IPWright83** [strapi/strapi-docker#209]
I'm trying to work out how I can establish a connection to a MongoDB replica set within the Strapi docker config for deploying to production.

At the moment I'm using something like this:

```
strapi:
    image: strapi/strapi
    container_name: strapi-cms
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo1
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password123
```

The problem is really my connection string needs to be `mongo1:27017,mongo2:27018,mongo3:27019`. This above only works when the primary is up and running. 

How do I go about configuring this for a replica set? I've tried just excluding the ports and providing the longer string as the `DATABASE_HOST` but unfortunately that doesn't seem to work.
