### ISSUE TITLE
Strapi docker mongodb atlas

### ISSUE THREAD

**Issue by iKethavel** [strapi/strapi-docker#214]
Hello!

I was trying to setup strapi via docker and connect it to [mongodb atlas](https://www.mongodb.com/cloud/atlas). And looks like approaches to replace mongodb atlas connetion string from [docs](https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#dynamic-configurations) and [video](https://www.youtube.com/watch?v=HHnRsZwFmR8&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=7&t=0s) works fine when we launch app via yarn or npm.
But what about docker? I still do not understand how to make it works :(
I could connect to this db via gui or mongoose:

```
version: '3'
services:

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_URI: mongodb+srv://arhe1:<password>@arhetericaclaster-5s8wz.mongodb.net/strapi?retryWrites=true&w=majority
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
```
