### ISSUE TITLE
Still getting connection REFUSED / RESET in a Docker-Compose install

### ISSUE THREAD

**Issue by brenojac** [strapi/strapi-docker#215]
Hello everyone,

I'm trying to run Strapi as suggested at https://strapi.io/documentation/3.0.0-beta.x/installation/docker.html

I read the previous thread on this issue (https://github.com/strapi/strapi-docker/issues/191) as well as the article suggested, which is pretty good and clear (https://pythonspeed.com/articles/docker-connection-refused/). While I'm able to reproduce running a web server on docker through binding it to 0.0.0.0 using python3 http.server, I'm unable to do it in Strapi, for some weird reason. My environment: Ubuntu 18.04 Desktop, with Docker and Docker-compose properly installed (latest version).  I have already tried the following: 

1) Downloaded the proper docker-compose file from the official documentation. I'm using a PGSQL DB: 
```

version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/data/postgres
    ports:
      - '5432:5432'

```
It runs and installs everything just fine: 

```
root@brenojac-Inspiron-3437:~/code/strapi# docker-compose up -d
Creating network "strapi_default" with the default driver
Creating strapi_postgres_1 ... done
Creating strapi_strapi_1   ... done


```   
I get this: 

```
This site can’t be reached 

localhost refused to connect.

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

```
2) Checking if there's any binding to 127.0.0.1. I could not find one. In fact, the files I get when running docker-compose are the following: 

```
root@brenojac-Inspiron-3437:~/code/strapi/app# ls -lah
total 524K
drwxr-xr-x   9 root root 4,0K jun 16 20:20 .
drwxr-xr-x   4 root root 4,0K jun 16 20:07 ..
drwxr-xr-x   2 root root 4,0K jun 16 19:26 api
drwxr-xr-x   2 root root 4,0K jun 16 19:29 build
drwxr-xr-x   5 root root 4,0K jun 16 19:28 .cache
drwxr-xr-x   3 root root 4,0K jun 16 19:26 config
-rw-r--r--   1 root root  249 jun 16 19:26 .editorconfig
-rw-r--r--   1 root root   23 jun 16 19:26 .env.example
-rw-r--r--   1 root root   32 jun 16 19:26 .eslintignore
-rw-r--r--   1 root root  541 jun 16 19:26 .eslintrc
drwxr-xr-x   2 root root 4,0K jun 16 19:26 extensions
-rw-r--r--   1 root root 1,2K jun 16 19:26 favicon.ico
-rw-r--r--   1 root root 1,1K jun 16 19:26 .gitignore
drwxr-xr-x 996 root root  36K jun 16 19:28 node_modules
-rw-r--r--   1 root root  877 jun 16 19:26 package.json
drwxr-xr-x   3 root root 4,0K jun 16 19:26 public
-rw-r--r--   1 root root   69 jun 16 19:26 README.md
-rw-r--r--   1 root root 418K jun 16 19:27 yarn.lock
```

Checked .env.example and even renamed it to .env: 

```
HOST=0.0.0.0
PORT=1337
```

Restarted and..  no deal. I tried to find any other configuration files and could find only config/server.js, whose contents are: 

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
});

```
So that pretty much exausts my possibilities. I'm quite new to docker, but I consider to have a good networking and linux background... if there's any other action I could take to solve this issue, please let me know. 

   

BTW your project is great. Actually it's beautiful. Thanks. 

regards,

- Breno
