### ISSUE TITLE
Strapi with docker-compose is unable to reinstall node_modules

### ISSUE THREAD

**Issue by MartinN3** [strapi/strapi-docker#225]
EDIT: MORE CONTEXT

Problem is that when you actually develop strapi, you commit app without node_modules and other trash. When you checkout that repo and do `docker-compose up` the strapi is unable to install missing NODE_MODULES ..... 

Filesystem volume snapshot:
```
docker-compose.yaml
app
    api
    components
    config
    exports
    extensions
    public
    .editorconfig
    .eslintignore
    .eslintrc
    .gitignore
    favicon.ico
    package.json
    README.md
```

```
version: "3"

services:
  strapi:
    image: strapi/strapi:3.0.5-node12-alpine
    container_name: strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "3000:1337"

etc.....
```

docker-compose up

```
strapi | Node modules not installed. Installing...
strapi | Starting your app...
strapi | Error loading the local develop command. Strapi might not be installed in your "node_modules". You may need to run "npm install"
```
