### ISSUE TITLE
Having an install issue in Azure Containers

### ISSUE THREAD

**Issue by jdnow** [strapi/strapi-docker#229]
Attempting to spin up a Strapi docker instance in Azure Containers, I'm using a configuration to build the setup:

```
apiVersion:` '2019-12-01'
location: centralus
name: <removed>
properties:
  containers:
  - name: strapitest
    properties:
      environmentVariables:
        - name: 'DATABASE_CLIENT'
          value: 'postgres'
        - name: 'DATABASE_NAME'
          value: <removed>
        - name: 'DATABASE_HOST'
          value: <removed>
        - name: 'DATABASE_PORT'
          value: '5432'
        - name: 'DATABASE_USERNAME'
          value: <removed>
        - name: 'DATABASE_PASSWORD'
          value: <removed>
        - name: 'DATABASE_SSL'
          value: 'true'
      image: strapi/strapi
      ports:
      - port: 1337
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
      volumeMounts:
      - mountPath: /srv/app
        name: strapisharevolume
  - name: nginx-with-ssl
    properties:
      image: nginx
      ports:
      - port: 443
        protocol: TCP
      - port: 80
        protocol: TCP
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
      volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
      - port: 443
        protocol: TCP
      - port: 80
        protocol: TCP
      - port: 1337
        protocol: TCP
    dnsNameLabel: <removed>
  volumes:
  - name: strapisharevolume
    azureFile:
      sharename: strapishare
      storageAccountName: <removed>
      storageAccountKey: <removed>
  - name: nginx-config
    azureFile:
      sharename: nginxconf
      storageAccountName: <removed>
      storageAccountKey: <removed>
tags: {}
type: Microsoft.ContainerInstance/containerGroups
```

Everything installs alright, but quickly run into an error on the startup of strapi:

```
Starting your app...
[2020-07-23T15:29:43.524Z] debug ⛔️ Server wasn't able to start properly.
[2020-07-23T15:29:43.526Z] error Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /srv/app/node_modules/sharp/lib/constructor.js
- /srv/app/node_modules/sharp/lib/index.js
- /srv/app/node_modules/strapi-plugin-upload/services/image-manipulation.js
- /srv/app/node_modules/strapi/lib/load/load-files.js
- /srv/app/node_modules/strapi/lib/core/load-apis.js
- /srv/app/node_modules/strapi/lib/core/load-modules.js
- /srv/app/node_modules/strapi/lib/Strapi.js
- /srv/app/node_modules/strapi/lib/index.js
- /srv/app/node_modules/strapi/lib/commands/develop.js
- /usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/srv/app/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/srv/app/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

```
