### ISSUE TITLE
Not able to create project with Docker

### ISSUE THREAD

**Issue by kaioduarte** [strapi/strapi-docker#230]
I followed the steps mentioned [in the docs](https://strapi.io/documentation/v3.x/installation/docker.html) and it's failing during the dependencies installation.

![image](https://user-images.githubusercontent.com/11046907/88316380-ab474680-cd0f-11ea-9755-6ffa5e7a78f0.png)

**Comment by Eventyret** [comment]
Could you share your docker file or docker-compose file @kaioduarte  ?

**Comment by kaioduarte** [comment]
Here it's

```yaml
version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
```
