### ISSUE TITLE
Deploy Frontend UI and API on Different Docker Containers (Docker Compose)

### ISSUE THREAD

**Issue by netlander** [strapi/strapi-docker#247]
-  [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Would be great if we could have devs provide docker-compose files for deploying the frontend UI and backend API on separate docker containers for use in swarm/stack deployment.

**Comment by derrickmehaffy** [comment]
I've transferred this over to our Docker repo as it's not directly related to the Strapi code-base, but implementation using docker

**Comment by GaxZE** [comment]
I've been playing around with compose and strapi for the last few days. My docker-compose file so far: 

```yaml
version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 1337:1337
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    depends_on:
      - db
    networks:
      - strapi-app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    tty: true
    stdin_open: true
    depends_on:
      - backend
    networks:
      - strapi-app-network

  db:
    container_name: strapi_db
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    networks:
      - strapi-app-network

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - strapi-app-network

networks:
  strapi-app-network:
    driver: bridge

volumes:
  pgdata:
```

Some notes: 
- I have an `.env` file for the environment variables.
- Frontend is merely just `create-react-app` application.
- This is specifically to utilise `postgres` as db but I've tried with Mongo and that worked as well.
- I've added `pgadmin` for a db GUI.

Hope this helps somebody.
