### ISSUE TITLE
Make sure the directory ./config/environments/production exists

### ISSUE THREAD

**Issue by wahengchang** [strapi/strapi-docker#249]
I am trying to connect `strapi` with mlab, and I fellowed what the `doc`'s step.
and I modified `.env` as the mlab config 

this is` docker-compose.yml`

```
#docker-compose.yml
version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: production
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
```

when i run
```
$ docker-compose up 
```

and run 
```
$ docker-compose up 
Recreating strapi ... done
Attaching to strapi
strapi    | Starting your app...
strapi    | Missing environment config for env: production.
strapi    | Make sure the directory ./config/environments/production exists
strapi exited with code 1
```
