### ISSUE TITLE
docker image failed to start 

### ISSUE THREAD

**Issue by hbakhtiyor** [strapi/strapi-docker#277]
just followed the instruction of the [guide ](https://strapi.io/documentation/developer-docs/latest/installation/docker.html) with such docker-compse.yaml

```
version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
```

and got such error

```
Starting your app...

Error loading the local develop command. Strapi might not be installed in your "node_modules". You may need to run "npm install"
```

os: windows 10 home

![image](https://user-images.githubusercontent.com/3434496/108083940-73ca2e00-7095-11eb-9a52-b409ccfcd2cf.png)
