### ISSUE TITLE
Azure Docker Compose Strapi/Strapi container - List of failed dependancies on deployment

### ISSUE THREAD

**Issue by j4t1nd3r** [strapi/strapi-docker#281]
### Describe the bug
I followed this guide: https://strapi.io/blog/how-to-run-a-strapi-dev-stack-with-docker-compose
Shifting from local to cloud: 
deploying strapi/strapi + mongo on Azure, strapi/strapi has a multitude of errors + takes 50 mins to roughly get through dependancies where on my local machine container is deployed in 5 mins.
### Steps to reproduce the behavior

1) docker compose up
2) See error in logs

### Expected behavior

No dependancy errors / dependancies installed faster than 50 mins

### Screenshots

Container stack deployed locally:
![local](https://user-images.githubusercontent.com/44571350/108083214-c17d7100-706a-11eb-9c0f-e2c8cdd01194.png)
Deployed in Cloud:
![cloud](https://user-images.githubusercontent.com/44571350/108083219-c3dfcb00-706a-11eb-81d6-936d444eaf8f.png)

### Code snippets
docker-compose.yml:
```
version: "3.8"

services:
  dido_strapi:
    image: strapi/strapi
    container_name: didostrapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - app:/srv/app  
    ports:
      - "1337:1337"

  dido_mongo:
    image: mongo
    container_name: didomongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db/
    ports:
      - "27017:27017"
networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
    driver: azure_file
    driver_opts:
      share_name: strapidata
      storage_account_name: didostorage
  app:
    driver: azure_file
    driver_opts:
      share_name: strapidata
      storage_account_name: didostorage
```
Azure / Docker commands ran
```
# creation of resources
New-AzResourceGroup     -name $rgname -location $location
New-AzContainerRegistry -ResourceGroupName $rgname -name $acrname -sku Basic -EnableAdminUser
New-AzStorageAccount    -ResourceGroupName $rgname -Name $storgname -Location $location -SkuName Standard_LRS
# new resources as variables
$rg         = Get-AzResourceGroup     -name $rgname
$reg        = Get-AzContainerRegistry -ResourceGroupName $rgname -name $acrname
$storgaccnt = Get-AzStorageAccount    -ResourceGroupName $rgname -Name $storgname
# login to az container
$creds = Get-AzContainerRegistryCredential -ResourceGroupName $rgname -name $acrname
$creds.Password | docker login $reg.LoginServer -u $creds.Username --password-stdin

# # Docker
docker context use default
docker pull strapi/strapi
docker pull mongo
# tag docker images
docker tag strapi/strapi didocontreg.azurecr.io/didostrapi
docker tag mongo didocontreg.azurecr.io/didomongo
# push docker images
docker push didocontreg.azurecr.io/didomongo
docker push didocontreg.azurecr.io/didostrapi
# check acr repo for images
az acr repository show -n $acrname --repository didostrapi
az acr repository show -n $acrname --repository didomongo
# docker / azure login setup
 # az context
docker context create aci az_dido --resource-group dido-poc
docker context use az_dido
# create docker volumes
docker volume create app --storage-account $storgname
docker volume create strapidata --storage-account $storgname

# run container instance
docker compose --project-name $continst 
```

### System

- Node.js version:  12.20.1
- NPM version:  6.14.10
- Strapi version: 3.4.6
- Database: Mongo
- Operating system: Alpine (docker container)
