### ISSUE TITLE
Strapi fails to replicate files in docker volume on Windows 10 64 Bit

### ISSUE THREAD

**Issue by sagefarrenholz** [strapi/strapi-docker#294]
My project is extremely simple. Just a folder called `strapi` in the root of the project directory. I want to volume mount that to /srv/app.

`docker-compose.yml`:
```
version: "3.9"
services:
  strapi:
    image: strapi/strapi:latest
    volumes:
       - ./strapi:/srv/app
    ports:
      - '1337:1337'
```

I have deleted the entire container and retried a few times. It launches fine but the volume is never populated, so if I delete the container obviously nothing persists. Investigating using `docker inspect` seems to show everything in order. I am running this on a SMB share on Windows 10 64 bit. It works fine on my Mac and Linux workstation oddly (even off the same network share).  This issue seems to be the same as found [here](https://stackoverflow.com/questions/60938698/bootstrap-strapi-with-docker-compose) on StackOverflow. Doesn't look resolved.

### Reproduce: 
Run `docker-compose up` with the above `docker-compose.yml`
Possibly do to being on a SMB share and / or Win 10?
