### ISSUE TITLE
not working after set mongo root username/password

### ISSUE THREAD

**Issue by axe-me** [strapi/strapi-docker#32]
docker-compose.yml:

```yml
version: '3'

services:
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=dbusername
      - DATABASE_PASSWORD=dbpassword
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dbusername
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dbpassword
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
```

error message:

```bash
db_1   | 2018-06-15T04:43:27.831+0000 I ACCESS   [conn121] SCRAM-SHA-1 authentication failed for dbusername on strapi from client 172.21.0.3:42320 ; UserNotFound: Could not find user dbusername@strapi
db_1   | 2018-06-15T04:43:27.832+0000 I NETWORK  [conn121] end connection 172.21.0.3:42320 (0 connections now open)
api_1  | [2018-06-15T04:43:27.832Z] warn Database connection has failed! Make sure your database is running.
```

**Comment by johannpinson** [comment]
@ShaneXie 

You need replace the variables into the `db` container by:
- MONGO_INITDB_ROOT_USERNAME
- MONGO_INITDB_ROOT_PASSWORD

**Comment by ShaneXie** [comment]
@johannpinson thanks, gonna try after work today.

**Comment by ShaneXie** [comment]
i think this is related to https://github.com/strapi/strapi-docker/issues/19, i prob just use empty db auth for now for dev until that fixed.

**Comment by lucaperret** [comment]
Hello @ShaneXie , could you retry with the latest image ?

**Comment by daniloferreiradasilva** [comment]
I had the same issue. Only setting the env var _MONGO_INITDB_DATABASE_  do not make the database be created. So your problem is that strapis database do not exists.

- You have to create a script (**myscript.sh**) inside a folder (**script-folder**)  
```
#!/usr/bin/env bash

echo 'Creating application user and db'

mongo ${MONGO_INITDB_DATABASE} \
        --host localhost \
        --port ${MONGO_PORT} \
        -u ${MONGO_INITDB_ROOT_USERNAME} \
        -p ${MONGO_INITDB_ROOT_PASSWORD} \
        --authenticationDatabase admin \
        --eval "db.createUser({user: '${DATABASE_USERNAME}', pwd: '${DATABASE_PASSWORD}', roles:[{role:'dbOwner', db: '${MONGO_INITDB_DATABASE}'}]});"
```

- and put it into /docker-entrypoint-initdb.d of the container
 volumes:
      - ./db:/data/db
      - ./**script-folder**/:/docker-entrypoint-initdb.d

But only works the first time you run the service, so you'll have to delete your volume.

**Comment by lucaperret** [comment]
If you set `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD`, you should also update environment variables in the `api` service:
- `DATABASE_USERNAME`
- `DATABASE_PASSWORD`
The image will use the root access for database login. It is only for the getting-started guide and dev purposes.

**Comment by panosru** [comment]
I bump on the same issue today, I wanted to try strapi, this is my `docker-compose.yml` file:

```yml
version: '3'

services:
  strapi-api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=foobar
      - DATABASE_PASSWORD=123123
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - strapi-db
    restart: always

  strapi-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foobar
      - MONGO_INITDB_ROOT_PASSWORD=123123
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always

networks:
  default:
    external:
      name: webservices
```

This is what I'm getting:
![image](https://user-images.githubusercontent.com/400362/51429915-b1410080-1c1c-11e9-950b-e798b9ef283f.png)

I also tried to replace `- HOST=localhost` with `- HOST=strapi-db` but I got the same result.

Thanks

**Comment by lauriejim** [comment]
Can you give us an update please.
Based on last version of files.

**Comment by FDiskas** [comment]
I got the same error but in different project. 
In my case there was error in conection string
was missing this:
```
...?authSource=admin
```
It could be related to this issue to: https://github.com/strapi/strapi/blob/a42c2a483ca6e35a25c7d214bedd2e0cefc48dbb/packages/strapi-hook-mongoose/lib/index.js#L89

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Comment by paradox42** [comment]
Anyone else were able to reproduce this?
I had the same issue with changing docker-compose file --> `docker-compose up -d` .
Find out I'll have to manually shut the containers down `docker-compose down` and then bring it back `docker-compose up` for be able to reload my docker-compose.yml new configuration.

Here is my mongodb service config section:
```
version: "3"
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    command: [--auth]
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js.js:ro
    environment:
      - MONGO_INITDB_DATABASE=nodebb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
```
