### ISSUE TITLE
V4 images on DockerHub

### ISSUE THREAD

**Issue by mooxl** [strapi/strapi-docker#321]
When will the images be officially pushed to V4 on DockerHub?

**Comment by kwiat1990** [comment]
I was a bit confused when I followed the Docker installation on documentation page for Strapi v4 and got v3.6.8 in the end. Docs should point out that it's not yet an v4 image, otherwise people waste their time ;)

**Comment by badan-cloud** [comment]
Same issue here.

**Comment by magisters-cc** [comment]
Same here.

**Comment by degitgitagitya** [comment]
Waiting for this to migrate

**Comment by oghea** [comment]
same issue here

**Comment by av1la** [comment]
same here

**Comment by benjaminpreiss** [comment]
Same here

**Comment by Slazerslaze** [comment]
Same here

**Comment by LeBenLeBen** [comment]
Please use the 👍 reaction on the initial message to share your interest. Posting the same message over and over creates noise by notifying everyone following this thread for no added value.

**Comment by badan-cloud** [comment]
> Same here
> 
> There is a workaround though to get it running relatively easy in the meanwhile. Create a local copy of the [Dockerfile](https://github.com/strapi/strapi-docker/blob/master/strapi/Dockerfile) and [entrypoint script](https://github.com/strapi/strapi-docker/blob/master/strapi/docker-entrypoint.sh). Then adjust [this line](https://github.com/strapi/strapi-docker/blob/263a0e4085c4a0615cdfba2b7728ca1e30c25753/strapi/Dockerfile#L5) in the Dockerfile to reference a different package: `RUN yarn global add @strapi/strapi@${STRAPI_VERSION}`.
> 
> Here is the updated [Dockerfile](https://github.com/benjaminpreiss/strapi-docker/blob/master/strapi/Dockerfile)

Nope. In the background it tries to install the needed version from the yarn repository, but the latest version of strapi in yarn is:

```
yarn info strapi
...
    '3.6.8': '2021-08-24T09:01:20.840Z'
```

**Comment by kevinlaw91** [comment]
> Nope. In the background it tries to install the needed version from the yarn repository, but the latest version of strapi in yarn is:
> 
> ```
> yarn info strapi
> ...
>     '3.6.8': '2021-08-24T09:01:20.840Z'
> ```

They changed the npm package name from ```strapi``` to ```@strapi/strapi```

**Comment by giorgiPapava** [comment]
Is there any way to upgrade current Strapi v3 with docker to v4?

**Comment by ziudeso** [comment]
Here's my 2 cents

Docker-compose.yml
```
version: "3"

services:
  strapi:
    # image: strapi/strapi
    build: 
      context: .
      args:
        BASE_VERSION: latest
        STRAPI_VERSION: 4.0.0
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_PORT_PROD: ${DATABASE_PORT_PROD}
      DATABASE_USERNAME_PROD: ${DATABASE_USERNAME_PROD}
      DATABASE_PASSWORD_PROD: ${DATABASE_PASSWORD_PROD}
      DATABASE_HOST_PROD: ${DATABASE_HOST_PROD}
      DATABASE_NAME_PROD: ${DATABASE_NAME_PROD}
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
      - .:/srv/app
    ports:
      - "1337:1337"
```

Dockerfile

```
ARG BASE_VERSION
FROM strapi/base:${BASE_VERSION}

ARG STRAPI_VERSION
RUN yarn global add @strapi/strapi@${STRAPI_VERSION}

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app

VOLUME /srv/app

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/docker-entrypoint.sh 
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["strapi", "develop"]
```
 
and finally the `docker-entrypoint.sh` is exactly the same as in this repo.
