### ISSUE TITLE
/admin showing nothing

### ISSUE THREAD

**Issue by albertorm95** [strapi/strapi-docker#35]
I have strapi running on a single node Swarm Cluster, I'm able to access the first page `You are looking at: ./public/index.html.` but when I try to go to `/admin` nothing show up, only a white page with the tittle Strapi Admin and the Icon, this is what I get from:

Network:
![screen shot 2018-07-04 at 4 42 20 pm](https://user-images.githubusercontent.com/8814890/42294795-70d857c4-7fa9-11e8-9859-db05fcbad84e.png)

Console:
![screen shot 2018-07-04 at 4 42 56 pm](https://user-images.githubusercontent.com/8814890/42294797-7716ffaa-7fa9-11e8-8960-737d0627f10f.png)

Elements:
![screen shot 2018-07-04 at 4 42 44 pm](https://user-images.githubusercontent.com/8814890/42294803-8519c182-7fa9-11e8-9097-03eef05c20c5.png)

docker-compose.yml

```
version: '3.6'

services:
  strapi:
    image: strapi/strapi:v3.0.0-alpha.12.4
    environment:
      - APP_NAME=app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=ip
      - DATABASE_PORT=port
      - DATABASE_NAME=database
      - HOST=localhost
    ports:
      - 5060:1337
    volumes:
      - /data/disk1/strapi:/usr/src/api/app
    deploy:
      replicas: 1
```
Logs:
![screen shot 2018-07-05 at 10 40 41 am](https://user-images.githubusercontent.com/8814890/42333292-f69242b2-803f-11e8-8e68-8b8376bfc494.png)
