### ISSUE TITLE
Docker stack

### ISSUE THREAD

**Issue by lishine** [strapi/strapi-docker#78]
Using docker stack deploy instead of docker-compose
Strapi cannot connect to the db
Here is the YML
```
version: "3"

services:

  strapi:
    image: salsa_api
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - w1
    ports:
      - "1337:1337"
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      # - /usr/src/api/strapi-app/node_modules
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "27017:27017"
    networks:
      - w1
    volumes:
      - ./db:/data/db

networks:
  w1:

```
