### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by panosru** [strapi/strapi-docker#85]
It seems that strapi is unable to connect to the database.

this is my `docker-compose.yml` file:

```yml
version: '3'

services:
  strapi-api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=foobar
      - DATABASE_PASSWORD=123123
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=strapi-db
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - strapi-db
    restart: always

  strapi-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foobar
      - MONGO_INITDB_ROOT_PASSWORD=123123
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always

networks:
  default:
    external:
      name: webservices
```

This is what I'm getting:
![image](https://user-images.githubusercontent.com/400362/51432231-d6456b80-1c3c-11e9-96f3-0bc53f5305ba.png)

![image](https://user-images.githubusercontent.com/400362/51429915-b1410080-1c1c-11e9-950b-e798b9ef283f.png)

Thanks

Related issue: #32
